### ISSUE TITLE
Add new option for vertical left and right

### ISSUE THREAD

**Issue by muuvmuuv** [sindresorhus/cli-boxes#8]
I would like to create a box which has arrows pointing to the center:

```
↘↓↓↓↓↓↓↙
→ Box  ←
↗↑↑↑↑↑↑↖
```

But this is not possible at the moment because there is just one vertical option. I suggest making it optional and add `verticalLeft` and `verticalRight`. No breaking change, just an add-on.

**Comment by sindresorhus** [comment]
Sure. Pull request welcome. Needs tests, docs, and index.d.ts updates.
